import Head from "next/head";
import Link from "next/link";
import {Layout} from "antd";

import Navbar from "../components/Navbar";
import LayoutContainer from "../components/LayoutContainer";
import EventGallery from "../components/EventGallery";

const {Footer} = Layout;

interface Props {}

const Home: React.FC<Props> = () => {
  return (
    <>
      <Head>
        <title>Que sale?</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Layout>
        <Navbar />
        <LayoutContainer
          title={
            <>
              Eventos en <Link href="/">Ciudad Autonoma de Buenos Aires</Link>
            </>
          }
        >
          <EventGallery />
        </LayoutContainer>
        <Footer style={{textAlign: "center"}}>Ant Design ©2018 Created by Ant UED</Footer>
      </Layout>
    </>
  );
};

export default Home;
